version: 2

# Build configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

# Package installation
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Sphinx
sphinx:
  configuration: docs/source/conf.py


